name: Build Validation

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Validate Python Syntax
        run: python -m py_compile app.py